** -*- koshu -*-
**
**  DESCRIPTION
**    F of X  ==  F X
**    X to F  ==  F X
**

|== P : add /x ( times ( 1 + 2 )( 3 + 4 ))
            /y ( double ( double ( double ( 5 + 6 ))))
        -where times x y = x * y
             : double x  = 2 * x

|== Q : add /x ( times of 1 + 2 of 3 + 4 )
            /y ( 5 + 6 to double to double to double )
        -where times x y = x * y
             : double x  = 2 * x
