**
**  DATASETS
**    There are changes C when altering dataset B into A.
**
**      B (base)    : B.k
**      A (altered) : A.k
**      C (change)  : A - B
**
**  UPDATE
**    Dataset A is obtained by updating B by C.
**    Please execute: koshu-change B -u C
**

|-X P  /x 1  /y 30
|-X Q  /y 20  /z 90
|-X Q  /y 40  /z 100
|-- P  /x 2  /y 50
|-- R  /x 1  /y 20  /z 90

*** 5 judges

**
**  SUMMARY
**       2 judges on P
**       2 judges on Q
**       1 judge  on R
**       5 judges in total
**
